### ISSUE TITLE
Own packages

### ISSUE THREAD

**Issue by Gi972** [elbywan/bosket#11]
Hello,

Do you think it possible to separate each module with his own package.
I mean instead have "bosket/react" , the package was "bosket-react"  for example with only file for react,
one for vue => "bosket-vue"  etc etc...

Because I use unpkg.com for load package  like a cdn in my project , and I would like make demo with playground editor like https://stackblitz.com/ 

Other thing, I see You use typescrpit can you put a file typescript definition file in the root of project ? I would like use the intellisence of typescript. thanks for your answer

**Comment by elbywan** [comment]
Hello @Gi972,

>Do you think it possible to separate each module with his own package.

Yes, I've been thinking about having separate npm packages for each framework.
I haven't done this yet because it's much easier for me to deploy if there is only a single bosket package.

Anyway, to do this properly, I have to : 
- create a @bosket npm organisation
- separate package into `@bosket/react` `@bosket/angular` `@bosket/vue` `@bosket/riot` `@bosket/tools` `@bosket/core`
- bundle each package in UMD format (for cdn support) AND es2015 modules (for tree-shaking)
- create deployment scripts to increment the package.json versions and deploy every package in a single step
- update the documentation

I won't be able to start working on it until next monday, and it will surely take a couple of days. Also it will be a **breaking change**.

> Other thing, I see You use typescrpit can you put a file typescript definition file in the root of project ?

Regarding typescript, it's only for angular users and it should already work (I tried in vscode I had autocompletion). For react users I made flowtype files.

**Comment by elbywan** [comment]
Done !

You can check out examples of working jsfiddle :

- [react](https://jsfiddle.net/elbywan/grL1prck/)
- [riot](https://jsfiddle.net/elbywan/w17o67vw/)
- [vue](https://jsfiddle.net/elbywan/dbsb7yhc/)

And stackblitz :

- [angular](https://stackblitz.com/edit/bosket-angular)
- [react](https://stackblitz.com/edit/bosket-react)

**Comment by Gi972** [comment]
Good job man 👍 

:-)
