### ISSUE TITLE
Drag and drop issues

### ISSUE THREAD

**Issue by nevf** [elbywan/bosket#2]
When you use drag & drop there is no indication where the drop will occur. 

Also the entire branch appears selected, although I'm only dragging a single item, 

Finally I'm unable to drop an item so that it becomes an descendant of an item.

You might want look at using Dragula https://github.com/bevacqua/dragula instead of what I assume is your own d&d implementation.

**Comment by elbywan** [comment]
I'm sorry but seems like I cannot reproduce those drag'n'drop issues.

> When you use drag & drop there is no indication where the drop will occur.

Actually, there is. A css class (.dragover) is added on hover, which in the demo is [clearly visible](https://image.ibb.co/kc7f15/sample.gif).

> Also the entire branch appears selected, although I'm only dragging a single item,

You mean the drag image ? If you are dragging a folder, then you will see the folder and its contents.
And the image is customizable anyway.

> Finally I'm unable to drop an item so that it becomes an descendant of an item.

You can pass a callback on drop to do anything, including turning items into folders and pushing the dropped item(s) inside.
I just didn't include it in the demo.

> You might want look at using Dragula https://github.com/bevacqua/dragula instead of what I assume is your own d&d implementation.

It's not my implementation actually, it's a thin wrapper around the [standard HTML drag'n'drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API).

**Comment by nevf** [comment]
@elbywan Ok.
1. Open https://elbywan.github.io/bosket/riot/index.html#TreeView#Demo  
2. Expand the Fruits and Vegetables node.
3. Drag Potato on to any Fruits item - there is no drop indication.

Also if you drag an item that is not at the root to the root _(say above Animals)_ there is no drop indication.

When a drop isn't possible the drag cursor should change to indicator this.

Tree drag and drop has lots of edge cases and is non-trivial to do properly, which is why I mentioned Dragula.

**Comment by elbywan** [comment]
@nevf This is how it renders from my side :

![gif](https://image.ibb.co/fhPZB5/dragsample.gif)

The gif quality sucks, opacity is much better in the browser.

> Drag Potato on to any Fruits item - there is no drop indication.

Not to be picky, but if I do just that I can see a box shadow around the whole Fruits list.  Plus the cursor changes with a + sign. Maybe a bit too transparent ?

Also I chose not to highlight single elements, because in this demo you cannot drop an element on top of another one except if the hovered element is a folder.

> Also if you drag an item that is not at the root to the root (say above Animals) there is no drop indication.

Again, opacity changes in the root list.

Anyway this is just a simple matter of css styling.

> When a drop isn't possible the drag cursor should change to indicator this.

Indeed and there is a cursor flickering issue also, will try to fix this.

> Tree drag and drop has lots of edge cases and is non-trivial to do properly, which is why I mentioned Dragula.

You're right, and the standard API is not that great actually.
 I will check out Dragula see if it's worth refactoring, thanks for suggesting this lib 😄

**Comment by elbywan** [comment]
Cursor flickering issues are fixed, but cannot change the cursor more than that. Browser implementations are lacking regarding the official dragndrop api.

I will consider a replacement in the future (dragula or something else).
