### ISSUE TITLE
doesn't load async children when searching

### ISSUE THREAD

**Issue by omnidan** [elbywan/bosket#20]
I would like to have my tree view search even in items that haven't been asynchronously loaded yet. So it would walk through the whole tree, resolve promises if they are not resolved yet and then search based on the results.

Right now when I search and the tree items haven't been expanded yet, they are not searched because their children weren't resolved yet.

**Comment by elbywan** [comment]
Hi @omnidan, right now it's just not possible because the component stores the filtered model inside its state (for performance reasons).
This filtered model is not updated when you update the regular model (for instance when you resolve the asynchronous items after typing something in the search input).

It is a simple change, but unfortunately I won't have time to work on it until this week end.
I'm going to update the issue afterwards with a little fiddle so you will have an example on how to do that !

**Comment by elbywan** [comment]
@omnidan I just released the fix.

I also made a little fiddle with comments [here](https://jsfiddle.net/elbywan/10w7qjkx/) on how to resolve promises while searching the tree.

Hope this will help 😃   !
