### ISSUE TITLE
Display method rendered as string not as html

### ISSUE THREAD

**Issue by sheriffmarley** [elbywan/bosket#54]
I need to wrap the item text in another label, but I have issues to add html to it.

I tried
```js
methods: {
display(item) {
                return '<a href="test">{ item.label }</a>'
            },
}
```

but this is rendered as string not as html. 

If I try to use this approch as used in the documentation section 
```js
data(){
   return {
    display: item => <a>{ item.label }</a>,
}
}
```
i'm not be able to get it compiled. Am I missing something, or is it a bug?

**Comment by elbywan** [comment]
@sheriffmarley I don't think that there is something wrong in the doc. since the demos seem to be working fine.

> i'm not be able to get it compiled.

If you get a compilation error, then something is wrong in your project configuration I guess. Try reading [the vuejs jsx guide](https://vuejs.org/v2/guide/render-function.html), and if you are using babel you might be missing the [right preset](https://github.com/vuejs/jsx).

**Comment by sheriffmarley** [comment]
Thought so too, but i cannot get it to build correctly I always either get a string or an compilation error:
And honestly i don't have any clue whats wrong. 

```js
ERROR in ./resources/assets/js/components/Filemanager/Tree.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/assets/js/components/Filemanager/Tree.vue?vue&type=script&lang=js&)
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\path\laravel\resources\assets\js\components\Filemanager\Tree.vue: Unexpected token (129:29)

  127 |                 }
  128 |             },
> 129 |             display: item => <a>{ item.label }</a>,
```
I just wanted to add a folder icon to the items if the item has no opener element.

**Comment by elbywan** [comment]
Seems like you are using `webpack` and `babel-loader`, I think that you are missing the right babel preset ([babel 7](https://github.com/vuejs/jsx) / [babel 6](https://github.com/vuejs/babel-plugin-transform-vue-jsx)).  

You need to install it and put it inside your babel configuration file, without it, babel does not "understand" how to transpile `jsx`.

You can also have a look at [this link](https://github.com/elbywan/bosket/issues/23) that might provide some help.

Closing the issue since it does not seem to be directly related to `bosket`.

**Comment by sheriffmarley** [comment]
Thanks you pointed me in the correct direction.  :)
For any other who is using laravel-mix . Add a .babelrc file to your project folder and install the this dependency https://github.com/vuejs/jsx  Then add the preset to it and you're good to go
