### ISSUE TITLE
Why npm -d?

### ISSUE THREAD

**Issue by Jon-Biz** [elbywan/bosket#6]
I'm unclear why it's recommended to install this package as a development dependency instead of a regular one. My linter is too.

tx.

**Comment by elbywan** [comment]
It's a dev dependency because it is assumed that you will bundle it with your app. 
If someone uses your app and installs it using npm, bosket will not be downloaded alongside.

Your linter is also a listed as a dev dependency because it is only required when building the app.

This [link](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies) should give you more details !

**Comment by Jon-Biz** [comment]
That's not what dev dependencies are for. 

Devdependencies include build tools, such as testing libraries, and other code that >isn't< going to be bundled with the app. If I publish my app on npm, I will want the bosket library to be a regular dependency, so that users implementing my library can install my module and getting it running with a simple npm i.  

This is not the same process as generating production code using a bundler, where all the dependencies get rolled up into one deliverable payload.

Unless they actually intend to alter code in the module I'm publishing itself, modifying code, or such as running the test suites etc, users of my module should not need to install it's development dependencies.

**Comment by elbywan** [comment]
> Devdependencies include build tools, such as testing libraries, and other code that >isn't< going to be bundled with the app. If I publish my app on npm, I will want the bosket library to be a regular dependency, so that users implementing my library can install my module and getting it running with a simple npm i.

You're right if you are building a consumable library built on bosket.

>This is not the same process as generating production code using a bundler, where all the dependencies get rolled up into one deliverable payload.

Since bosket is published as es2015 modules and not UMD, I assumed that most of the library consumers would use webpack / rollup or another build tool to pack up everything alongside the web framework. Thus eliminating the need for a regular bosket dependency.

But anyway, my bad for adding the `-D` flag. It was indeed a mistake and I will remove it.
